<a href="https://colab.research.google.com/github/sonukiran3101/Sonu07/blob/master/PDF_to_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install git+https://github.com/pdftables/python-pdftables-api.git

Collecting git+https://github.com/pdftables/python-pdftables-api.git
  Cloning https://github.com/pdftables/python-pdftables-api.git to /tmp/pip-req-build-c4n0rqxl
  Running command git clone -q https://github.com/pdftables/python-pdftables-api.git /tmp/pip-req-build-c4n0rqxl
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from pdftables-api==1.1.0) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->pdftables-api==1.1.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->pdftables-api==1.1.0) (2021.5.30)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->pdftables-api==1.1.0) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->pdftables-api==1.1.0) (2.10)
Building wheels for collected packages: pdftables-api
  Building wheel for pdftables-api (setup.py) ... done
  Created wheel for pdftables-api: filename=pdftables_api-1.1.0-cp37-none-any.whl size=5882 sha256=d7e244c3bfaa8d2f32dd6f4b8205268634189e1904715073c5af85dfe253837b
  Stored in directory: /tmp/pip-ephem-wheel-cache-7s35005r/wheels/49/66/c0/e4f778e772a77892a98b3aaaba300cbb27a29a07e0c225cd80
Successfully built pdftables-api
Installing collected packages: pdftables-api
Successfully installed pdftables-api-1.1.0

In [2]:
import pdftables_api

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [10]:
 # API KEY VERIFICATION
conversion = pdftables_api.Client('aio61n3i92db')

pdf_file_path = "/content/gdrive/My Drive/zignaa_analytics/Sample_Form.pdf"
output_file_path = "/content/gdrive/My Drive/zignaa_analytics/Sample_Form_csv.csv"
# PDf to CSV 
# (Hello.pdf, Hello)
conversion.csv(pdf_file_path, output_file_path)

In [11]:
import pandas as pd
df = pd.read_csv("/content/gdrive/My Drive/zignaa_analytics/Sample_Form_csv.csv")

In [13]:
df.head(30)

                                           Unnamed: 0  ...               Unnamed: 10
0          Name _P_e_r_s_o_n_ _N_m__a_e______________  ...           Emerging Talent
1                                                      ...  Key Function/Site Talent
2                                                      ...
3                              **All boxes associated  ...
4                                with a category/tier  ...
5                              must be checked for an  ...
6                             individual to be ADEPT.  ...
7                                                      ...
8   HIGH\nPERF-ORMANCE\nIs the TM ahigh performer?...  ...
9                                                      ...
10                                         ENGAGEMENT  ...
11                                    Is TM committed  ...
12                                                     ...
13                                    and will he/she  ...
14                                    remain with our  ...
15                                           company?  ...
16                                                     ...
17                                      * Stop if no,  ...
18                                 otherwise continue  ...
19                                                     ...
20                                                     ...
21                                                     ...
22                                         ASPIRATION  ...
23                                                     ...
24                                        Does the TM  ...
25                                                     ...
26                                        demonstrate  ...
27                                    career ambition  ...
28                                         and drive?  ...
29                                                     ...

[30 rows x 11 columns]

In [12]:
df = df.fillna(' ') # Replacing all the NAN values with empty string

In [ ]:
df.head(30)

                                           Unnamed: 0  ...               Unnamed: 10
0          Name _P_e_r_s_o_n_ _N_m__a_e______________  ...           Emerging Talent
1                                                      ...  Key Function/Site Talent
2                                                      ...
3                              **All boxes associated  ...
4                                with a category/tier  ...
5                              must be checked for an  ...
6                             individual to be ADEPT.  ...
7                                                      ...
8   HIGH\nPERF-ORMANCE\nIs the TM ahigh performer?...  ...
9                                                      ...
10                                         ENGAGEMENT  ...
11                                    Is TM committed  ...
12                                                     ...
13                                    and will he/she  ...
14                                    remain with our  ...
15                                           company?  ...
16                                                     ...
17                                      * Stop if no,  ...
18                                 otherwise continue  ...
19                                                     ...

[20 rows x 11 columns]